### ISSUE TITLE
serializer using ForeignKey causes SynchronousOnlyOperation error

### ISSUE THREAD

**Issue by xpecel** [em1208/adrf#43]
hi.
i try to serialize a model that has a relation to another model with a ForeignKey field, and i get an error message about django.core.exceptions.SynchronousOnlyOperation 

here is an example of my code,
```python
# models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

```
```python
# test.py
import asyncio
import os
import sys
from pathlib import Path

import django
from django.utils import timezone
from rest_framework import serializers
from adrf.serializers import Serializer

sys.path.append(str(Path.cwd()))

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "mysite.settings")
django.setup()

from polls.models import Choice, Question

"""
q = Question(
    question_text="how many legs does an elephant have?",
    pub_date=timezone.now(),
)
q.save()

c1 = Choice.objects.create(question=q, choice_text="four legs", votes=4)
c2 = Choice.objects.create(question=q, choice_text="five legs", votes=1)
c3 = Choice.objects.create(question=q, choice_text="three legs", votes=1)
"""


class ChoiceSerializer(Serializer):
    question = serializers.CharField(source="question.question_text")
    choice_text = serializers.CharField()
    votes = serializers.IntegerField()


async def main() -> None:
    query = Choice.objects.filter(question__id=1)
    serializer_data = ChoiceSerializer(query, many=True)
    result = await serializer_data.adata
    print(result)


if __name__ == "__main__":
    asyncio.run(main())

```

log,
```log
(testing) ▲ /t/testing python test.py
Traceback (most recent call last):
  File "/tmp/testing/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 36, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'question'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/testing/test.py", line 45, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/tmp/testing/test.py", line 40, in main
    result = await serializer_data.adata
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/async_property/base.py", line 37, in get_value
    return await self._fget(instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/adrf/serializers.py", line 228, in adata
    ret = await super().adata
          ^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/async_property/base.py", line 37, in get_value
    return await self._fget(instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/adrf/serializers.py", line 72, in adata
    self._data = await self.ato_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/adrf/serializers.py", line 184, in ato_representation
    return [await self.child.ato_representation(item) async for item in data]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/adrf/serializers.py", line 152, in ato_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/rest_framework/fields.py", line 437, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/rest_framework/fields.py", line 104, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/tmp/testing/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
(testing) ▲ /t/testing 
```

error will be gone if i remove `question = serializers.CharField(source="question.question_text")` from serializer class
```log
(testing) ▲ /t/testing python test.py
[OrderedDict({'choice_text': 'four legs', 'votes': 4}), OrderedDict({'choice_text': 'five legs', 'votes': 1}), OrderedDict({'choice_text': 'three legs
', 'votes': 1})]
(testing) ▲ /t/testing 
```

**Comment by CMarcher-Ahuora** [comment]
I have also encountered a very similar problem. Naturally, we have quite a few relations between our models, and any foreign key reference in the model seems to result in this error when attempting to make an asynchronous call to the corresponding serializer.

**Comment by Sauloopez** [comment]
That may be happening because the excecution on 

File "/tmp/testing/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/testing/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))

'qs' refers to QuerySet object, no? so...

wich applies only to synchronus operations or I'm wrong?

**Comment by xpecel** [comment]
sorry, this was supposed to be django issue, not adrf issue. so ill close this issue
